### ISSUE TITLE
Received feedback

### ISSUE THREAD

**Issue by rezaska** [rezaska/Projetc-1-Personal-blog-website#2]
Babak jan, here is the feedback I got for my project. 
I have already started to fix these issues.
What do you think?

https://review.udacity.com/#!/reviews/2346773

**Comment by babak1199** [comment]
Hi Alireza jaan, I don't have access to see the review via the link. It could be useful if you can take a screenshot or copy/paste it.

**Comment by rezaska** [comment]
I am going to close this one as well.
I will send you the feedback and we can discuss it over the phone when you have time.
